CREATE TABLE `callback_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int,
	`name` varchar(200) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`email` varchar(320),
	`preferredTime` varchar(100),
	`message` text,
	`status` enum('pending','called','no_answer','resolved') NOT NULL DEFAULT 'pending',
	`assignedTo` varchar(200),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `callback_requests_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `instruct_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int,
	`firmId` int NOT NULL,
	`firmName` varchar(255) NOT NULL,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`paymentAmount` decimal(10,2),
	`paymentStatus` enum('pending','paid','failed') NOT NULL DEFAULT 'pending',
	`stripePaymentIntentId` varchar(255),
	`status` enum('submitted','confirmed','in_progress','completed','cancelled') NOT NULL DEFAULT 'submitted',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `instruct_requests_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `law_firms` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`location` varchar(255),
	`phone` varchar(50),
	`email` varchar(320),
	`website` varchar(500),
	`regulatoryBody` enum('SRA','CLC') NOT NULL DEFAULT 'SRA',
	`sraNumber` varchar(50),
	`rating` decimal(3,2) DEFAULT '4.50',
	`reviewCount` int DEFAULT 0,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `law_firms_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`transactionType` enum('purchase','sale','sale_purchase','remortgage') NOT NULL,
	`propertyValue` int NOT NULL,
	`postcode` varchar(10) NOT NULL,
	`propertyTenure` enum('freehold','leasehold') DEFAULT 'freehold',
	`isFirstTimeBuyer` boolean DEFAULT false,
	`hasMortgage` boolean DEFAULT false,
	`mortgageLender` varchar(100),
	`isNewBuild` boolean DEFAULT false,
	`isSharedOwnership` boolean DEFAULT false,
	`isGiftedDeposit` boolean DEFAULT false,
	`hasHelpToBuyIsa` boolean DEFAULT false,
	`isRightToBuy` boolean DEFAULT false,
	`isBuyToLet` boolean DEFAULT false,
	`isSecondHome` boolean DEFAULT false,
	`numberOfBuyers` int DEFAULT 1,
	`hasMortgageOnSale` boolean DEFAULT false,
	`isTransferOfEquity` boolean DEFAULT false,
	`movingTimeline` varchar(100),
	`status` enum('new','contacted','instructed','lost') NOT NULL DEFAULT 'new',
	`actionTaken` enum('browsed','callback_requested','instructed') DEFAULT 'browsed',
	`selectedFirmId` int,
	`quotedLegalFee` decimal(10,2),
	`quotedTotal` decimal(10,2),
	`adminNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
